#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Running collectstatic..."
python /app/manage.py collectstatic --noinput

echo "Starting Gunicorn..."
exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:5000 --chdir=/app -k uvicorn.workers.UvicornWorker

tail -f /dev/null
